### ISSUE TITLE
Wagmi error:  r.connector.getChainId is not a function

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/bridge#200]
### Describe the problem you discovered

Error in grafana

```
[{"timestamp":"2024-10-29T23:37:06.645","message":"null - r.connector.getChainId is not a function - null - null - {}","level":"LogLevel.error","stacktrace":"\n    at Object.e (https://bridge.archethic.net/main.dart.js:3521:19)\n    at https://bridge.archethic.net/main.dart.js:38548:9\n    at br8.a (https://bridge.archethic.net/main.dart.js:4946:63)\n    at br8.$2 (https://bridge.archethic.net/main.dart.js:51568:14)\n    at bpC.$2 (https://bridge.archethic.net/main.dart.js:51565:16)\n    at ZD.AS (https://bridge.archethic.net/main.dart.js:52774:35)\n    at o8.aUB (https://bridge.archethic.net/main.dart.js:51876:18)\n    at bgp.$0 (https://bridge.archethic.net/main.dart.js:52025:37)\n    at Object.L_ (https://bridge.archethic.net/main.dart.js:5104:78)\n    at an.kT (https://bridge.archethic.net/main.dart.js:51952:3)","name":"EVMBridgeProcessMixin - EVMHTLCERC - approveChargeableHTLC"},{"timestamp":"2024-10-29T23:37:06.646","message":"e Failure.other(cause: null, stack: null)","level":"LogLevel.error","stacktrace":"\n    at Object.e (https://bridge.archethic.net/main.dart.js:3521:19)\n    at https://bridge.archethic.net/main.dart.js:61174:9\n    at br8.a (https://bridge.archethic.net/main.dart.js:4946:63)\n    at br8.$2 (https://bridge.archethic.net/main.dart.js:51568:14)\n    at bpC.$2 (https://bridge.archethic.net/main.dart.js:51565:16)\n    at ZD.AS (https://bridge.archethic.net/main.dart.js:52774:35)\n    at o8.aUB (https://bridge.archethic.net/main.dart.js:51876:18)\n    at bgp.$0 (https://bridge.archethic.net/main.dart.js:52025:37)\n    at Object.L_ (https://bridge.archethic.net/main.dart.js:5104:78)\n    at an.kT (https://bridge.archethic.net/main.dart.js:51952:3)","name":"EVMHTLCERC - approveChargeableHTLC"}]
```

**Comment by Chralu** [comment]
Might be related to #191 

To keep on watch, but should be closed within a few weeks if this does not occur anymore.
