### ISSUE TITLE
 Invalid SVG data

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/bridge#44]
### Describe the problem you discovered

When we launch the app, in the console javascript:
```
Uncaught Bad state: Invalid SVG data
    at Object.e (https://bridge.testnet.archethic.net/main.dart.js:2995:19)
    at os.ayN (https://bridge.testnet.archethic.net/main.dart.js:131356:63)
    at aVV.$1 (https://bridge.testnet.archethic.net/main.dart.js:114380:3)
    at Object.bTI (https://bridge.testnet.archethic.net/main.dart.js:38075:24)
    at aVW.$1 (https://bridge.testnet.archethic.net/main.dart.js:114369:10)
    at Wj.Vn (https://bridge.testnet.archethic.net/main.dart.js:49388:33)
    at b4W.$0 (https://bridge.testnet.archethic.net/main.dart.js:48700:11)
    at Object.IJ (https://bridge.testnet.archethic.net/main.dart.js:4524:40)
    at am.qr (https://bridge.testnet.archethic.net/main.dart.js:48623:3)
    at b4P.$0 (https://bridge.testnet.archethic.net/main.dart.js:48670:13)
```

**Comment by redDwarf03** [comment]
SVG fixed
