### ISSUE TITLE
SafePal - Pending request error

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/bridge#48]
### Describe the problem you discovered

AE -> Mumbai with Safepal wallet
When it was the withdraw, we don't receive from SafePal the request to sign the transaction.
We stopped the process and resume it. 
An error occurs:

```UnimplementedError: {
  "code": -32003,
  "message": "there is a pending request, please request after it resolved",
  "stack": "Error: there is a pending request, please request after it resolved\n    at a (chrome-extension://lgmpcpglpngdoalbgeoldeajfclnhafa/inpage.js:126:96799)\n    at Object.transactionRejected (chrome-extension://lgmpcpglpngdoalbgeoldeajfclnhafa/inpage.js:126:97929)\n    at d.call (chrome-extension://lgmpcpglpngdoalbgeoldeajfclnhafa/inpage.js:157:172579)\n    at Vd.request (chrome-extension://lgmpcpglpngdoalbgeoldeajfclnhafa/inpage.js:171:63509)\n    at Object.DartEthereum$124rawRequest [as DartEthereum|rawRequest] (http://localhost:51961/packages/webthree/src/browser/metamask/javascript.dart.lib.js:309:117)\n    at credentials$.MetaMaskCredentials.new.sendTransaction (http://localhost:51961/packages/webthree/src/browser/metamask/javascript.dart.lib.js:104:54)\n    at webthree.Web3Client.new.sendTransaction (http://localhost:51961/packages/webthree/src/credentials/wallet.dart.lib.js:2999:23)\n    at sendTransaction.next (<anonymous>)\n    at runBody (http://localhost:51961/dart_sdk.js:39921:34)\n    at Object._async [as async] (http://localhost:51961/dart_sdk.js:39957:7)\n    at webthree.Web3Client.new.sendTransaction (http://localhost:51961/packages/webthree/src/credentials/wallet.dart.lib.js:2997:20)\n    at evm_htlc_native.EVMHTLCNative.new.sendTransactionWithErrorManagement (http://localhost:51961/packages/aebridge/domain/usecases/bridge_evm_to_ae.dart.lib.js:761:51)\n    at sendTransactionWithErrorManagement.next (<anonymous>)\n    at http://localhost:51961/dart_sdk.js:39902:33\n    at _RootZone.runUnary (http://localhost:51961/dart_sdk.js:39737:59)\n    at _FutureListener.thenAwait.handleValue (http://localhost:51961/dart_sdk.js:35127:29)\n    at handleValueCallback (http://localhost:51961/dart_sdk.js:35709:49)\n    at _Future._propagateToListeners (http://localhost:51961/dart_sdk.js:35747:17)\n    at [_completeWithValue] (http://localhost:51961/dart_sdk.js:35588:23)\n    at async._AsyncCallbackEntry.new.callback (http://localhost:51961/dart_sdk.js:35622:35)\n    at Object._microtaskLoop (http://localhost:51961/dart_sdk.js:40214:13)\n    at _startMicrotaskLoop (http://localhost:51961/dart_sdk.js:40220:13)\n    at http://localhost:51961/dart_sdk.js:35968:9"
}, EVMBridgeProcessMixin - sendTransactionWithErrorManagement, dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:49  throw_
packages/webthree/src/core/exception_utils_js.dart 17:9                       analyzeException
packages/webthree/src/browser/metamask/dart_wrappers.dart 50:22               <fn>
dart-sdk/lib/async/future.dart 1069:25                                        onError
dart-sdk/lib/async/zone.dart 1666:54                                          runBinary
dart-sdk/lib/async/future_impl.dart 171:22                                    handleError
dart-sdk/lib/async/future_impl.dart 852:46                                    handleError
dart-sdk/lib/async/future_impl.dart 873:13                                    _propagateToListeners
dart-sdk/lib/async/future_impl.dart 649:5                                     [_completeError]
dart-sdk/lib/async/future_impl.dart 739:7                                     callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:15           <fn>
e Failure.other(cause: UnimplementedError: {
  "code": -32003,
  "message": "there is a pending request, please request after it resolved",
  "stack": "Error: there is a pending request, please request after it resolved\n    at a (chrome-extension://lgmpcpglpngdoalbgeoldeajfclnhafa/inpage.js:126:96799)\n    at Object.transactionRejected (chrome-extension://lgmpcpglpngdoalbgeoldeajfclnhafa/inpage.js:126:97929)\n    at d.call (chrome-extension://lgmpcpglpngdoalbgeoldeajfclnhafa/inpage.js:157:172579)\n    at Vd.request (chrome-extension://lgmpcpglpngdoalbgeoldeajfclnhafa/inpage.js:171:63509)\n    at Object.DartEthereum$124rawRequest [as DartEthereum|rawRequest] (http://localhost:51961/packages/webthree/src/browser/metamask/javascript.dart.lib.js:309:117)\n    at credentials$.MetaMaskCredentials.new.sendTransaction (http://localhost:51961/packages/webthree/src/browser/metamask/javascript.dart.lib.js:104:54)\n    at webthree.Web3Client.new.sendTransaction (http://localhost:51961/packages/webthree/src/credentials/wallet.dart.lib.js:2999:23)\n    at sendTransaction.next (<anonymous>)\n    at runBody (http://localhost:51961/dart_sdk.js:39921:34)\n    at Object._async [as async] (http://localhost:51961/dart_sdk.js:39957:7)\n    at webthree.Web3Client.new.sendTransaction (http://localhost:51961/packages/webthree/src/credentials/wallet.dart.lib.js:2997:20)\n    at evm_htlc_native.EVMHTLCNative.new.sendTransactionWithErrorManagement (http://localhost:51961/packages/aebridge/domain/usecases/bridge_evm_to_ae.dart.lib.js:761:51)\n    at sendTransactionWithErrorManagement.next (<anonymous>)\n    at http://localhost:51961/dart_sdk.js:39902:33\n    at _RootZone.runUnary (http://localhost:51961/dart_sdk.js:39737:59)\n    at _FutureListener.thenAwait.handleValue (http://localhost:51961/dart_sdk.js:35127:29)\n    at handleValueCallback (http://localhost:51961/dart_sdk.js:35709:49)\n    at _Future._propagateToListeners (http://localhost:51961/dart_sdk.js:35747:17)\n    at [_completeWithValue] (http://localhost:51961/dart_sdk.js:35588:23)\n    at async._AsyncCallbackEntry.new.callback (http://localhost:51961/dart_sdk.js:35622:35)\n    at Object._microtaskLoop (http://localhost:51961/dart_sdk.js:40214:13)\n    at _startMicrotaskLoop (http://localhost:51961/dart_sdk.js:40220:13)\n    at http://localhost:51961/dart_sdk.js:35968:9"
}, stack: null), EVMHTLCNative - signedWithdraw, dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:49  throw_
packages/aebridge/domain/usecases/bridge_evm_process_mixin.dart 367:7         sendTransactionWithErrorManagement
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 60:31            <fn>
dart-sdk/lib/async/zone.dart 1666:54                                          runBinary
dart-sdk/lib/async/future_impl.dart 171:22                                    handleError
dart-sdk/lib/async/future_impl.dart 852:46                                    handleError
dart-sdk/lib/async/future_impl.dart 873:13                                    _propagateToListeners
dart-sdk/lib/async/future_impl.dart 649:5                                     [_completeError]
dart-sdk/lib/async/future_impl.dart 739:7                                     callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:15           <fn>
```
![Capture d’écran 2023-11-21 à 21 08 59](https://github.com/archethic-foundation/bridge/assets/68340133/1ce911a6-9633-4773-98e9-41a565ad7750)

**Comment by redDwarf03** [comment]
Safepal seems not available anymore...
Dead ink : https://chrome.google.com/webstore/detail/safepal-extension-wallet/lgmpcpglpngdoalbgeoldeajfclnhafa

**Comment by redDwarf03** [comment]
Fixed by https://github.com/archethic-foundation/bridge/pull/113
